spring:
   profiles:
      active: dev-6868 
      
---
server:
   port: 6868
   
spring:
   profiles: dev-6868
   application:
      name: eureka-server
   security:
      user:
         name: yjj
         password: a

eureka:
   instance:
      hostname: localhost
   client:
      register-with-eureka: false
      fetch-registry: false
      serviceUrl:
         defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
      server:
         enable-self-preservation: false
         
---
server:
   port: 6869
   
spring:
   profiles: dev-6869
   application:
      name: eureka-server
   security:
      user:
         name: yjj
         password: a

eureka:
   instance:
      hostname: localhost
   client:
      register-with-eureka: false
      fetch-registry: false
      serviceUrl:
         defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
      server:
         enable-self-preservation: false
         