server:
   port: 9999
spring:
   application:
      name: fresh-zuul
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://yjj:a@127.0.0.1:6868/eureka
         
zuul:
   max:
      host:
         connections: 500
   host:
      maxTotalConnections: 200   #最大连接数
      maxPerRouteConnections: 20   #每个路由器的最大连接个数
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
   routes:
      service-rpc-user:
         path: /user/**
         serviceId: fresh-user
         #zuul在路由的时候，zuul会改写成request中的header信息，这个配置就是对那些header敏感，回过来这些header信息
         sensitiveHeaders: "*"
         
      service-rpc-goods:
         path: /goods/**
         serviceId: fresh-goods
         sensitiveHeaders: "*"
         
      service-rpc-order:
         path: /order/**
         serviceId: fresh-order
         sensitiveHeaders: "*"
         
ribbon:
   ReadTimeout: 10000   #小于zuul的超时时间
   ConnectTimeout: 10000
      